### ISSUE TITLE
Memory leak when using many ImagePixel widgets

### ISSUE THREAD

**Issue by reesz** [marcglasberg/image_pixels#1] opened 2021-01-18 09:17 UTC
We've wanted to incorporate more complex UIs with quite a couple of ImagePixel-widgets in our flutter app.
The results being that after loading around 20 sub-pages (closing every single one before opening the next) and populating an infinite scrolling list (even though using a SliverList.builder to not render more than needed) the apps memory started to run full, get laggy and crash consistently.

I think this might be due to the streams & eventListeners being created/added in `_GetImage.run():282` which never get removed. In other flutter example which do a similar thing, these listeners always get removed.

We've hat to ditch this feature and supply the colors manually, but it might be worth looking into.

**Comment by marcglasberg** [comment] 2021-01-18 13:19
I'll investigate and fix this. Is it possible that you provide me with a runnable example, as simple as possible?

**Comment by reesz** [comment] 2021-01-18 13:33
Once the app project is over I might be able to put something together.
For the time being I can try to specify what we had:

(If it matters: we were using a CupertinoTab-style app).
On the first tab we have a sliver list with every item being a rectangle that with some design around it contained this image in it's core:
```dart
String imageUrl = 'link_to_some_web_url_of_a_jpg_image';
CachedNetworkImage(
    fadeOutDuration: Duration.zero,
    imageUrl: imageUrl ?? '',
    fit: BoxFit.contain,
    imageBuilder: (context, imageProvider) {
        return ImagePixels(
            imageProvider: imageProvider,
            builder: (BuildContext context, ImgDetails img) {
                pixelColor = img.pixelColorAt(0, 0); // We're using this ImagePixels widget here to get the top, left color before transitioning to the detail-view, so the detail-view can be provided with it's background color.
                return Image(image: imageProvider, fit: BoxFit.contain);
            },
        );
    },
);
```

On the detail view there then was PageView-based-slider containing between 1-5 of these Image-Containers:
```dart
double screenWidth = MediaQuery.of(context).size.width;
Color defaultBgColor; // <-- this color is the one we retrieved as "pixelColor" on the page before and passed through Navigator-Route-Arguments.
// This was needed, since the we applied some scaling hero animation transformations on the main gallery image, resulting in the ImagePixels at some point "flickering" and resetting tot he `defaultColor` once the hero-animation switched elements or scaled too much.

return Container(
      height: screenWidth,
      child: CachedNetworkImage(
        fadeOutDuration: Duration.zero,
        imageUrl: imageUrl,
        fit: BoxFit.contain,
        imageBuilder: (context, imageProvider) {
          return ImagePixels.container(
            defaultColor: defaultBgColor ?? Colors.white,
            imageProvider: imageProvider,
            colorAlignment: Alignment.topLeft,
            child: Container(
              width: double.infinity,
              child: Image(image: imageProvider, fit: BoxFit.contain),
            ),
        },
      ),
    );
```
If we now scrolled through the main-tab and opened multiple detail-pages, which all rendered ~4 ImagePixel-containers. Returned and repeated this, you could watch the App's used RAM increase by around 100MB per page open, which after ~26 opens resulted in the crash.

If you haven't created a simple example yourself until then, I might be able to get back with something once I got some more time on my hands.

**Comment by marcglasberg** [comment] 2021-01-18 18:32
Could you please test if the problem is solved, or at least improved?

Please try version `1.0.3`, not yet published. Your `pubspec.yaml` may declare it like this: 

```
  image_pixels:
    git:
      url: https://github.com/marcglasberg/image_pixels
      ref: c68fe4ae6956ed578305294b6743e95f3544417a
```

**Comment by marcglasberg** [comment] 2021-01-24 16:56
@reesz Hey, did you have time to test this? Thanks.

**Comment by reesz** [comment] 2021-01-25 13:37
Sorry, didn't have the time to test, yet. I'm planing to release the project this week so I'll try the new version hopefully over the weekend 🙏

**Comment by reesz** [comment] 2021-02-09 11:31
Sorry for the delay. I finally got around to test it. With the first tests our app doesn't seem to be crashing anymore.
Also the developer instruments only show very minor increase in memory per page-open.

There's only one more error that pops up:
`image_pixels.dart:179`
If an ImagePixel-container is created and then destroyed before the Future is resolved, it causes ` setState() called after dispose()`.
So just checking if `widget.mounted` before calling `setState((){});` should solve this.

Thanks for looking into it, we'll do some more testing before we include it in production again, but if it'll make it into production again, I'll report back.

**Comment by marcglasberg** [comment] 2021-02-09 12:49
Ok, added `if (mounted)` to version [1.0.4].

I am closing this issue, but please reopen it if you still find any problems. Thanks!

**Closed as completed by marcglasberg** 2021-02-09 12:49 UTC
